#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# GitHub Repository Management for SaaS Validation System
# ============================================================================
# This script handles all GitHub repository operations:
# - Create new repositories
# - Initialize with main branch
# - Create feature branches
# - Setup branching strategy
# ============================================================================

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}ℹ${NC} $1"; }
log_success() { echo -e "${GREEN}✅${NC} $1"; }
log_warn() { echo -e "${YELLOW}⚠️${NC} $1"; }
log_error() { echo -e "${RED}❌${NC} $1"; }

# ============================================================================
# CONFIGURATION
# ============================================================================

REPO_NAME=${1:-""}
DESCRIPTION=${2:-"AI-generated landing page for SaaS validation"}
VISIBILITY=${3:-"private"}  # public or private
AUTO_INIT=${4:-"true"}
BRANCH_NAME=${5:-"feature/test-$(date +%s)"}

# Check if gh CLI is installed
check_gh_cli() {
  if ! command -v gh >/dev/null 2>&1; then
    log_error "GitHub CLI (gh) is not installed"
    log_info "Install with: brew install gh"
    log_info "Then authenticate: gh auth login"
    exit 1
  fi

  # Check if authenticated
  if ! gh auth status >/dev/null 2>&1; then
    log_error "GitHub CLI is not authenticated"
    log_info "Run: gh auth login"
    exit 1
  fi

  log_success "GitHub CLI ready"
}

# ============================================================================
# REPOSITORY CREATION
# ============================================================================

create_repository() {
  log_info "Creating GitHub repository: $REPO_NAME"

  # Create repo
  gh repo create "$REPO_NAME" \
    --description "$DESCRIPTION" \
    --$VISIBILITY \
    --source=. \
    --remote=origin \
    --push

  log_success "Repository created: https://github.com/$(git config get github.user)/$REPO_NAME"
}

initialize_repository() {
  log_info "Initializing repository structure"

  # Create .gitignore if not exists
  if [ ! -f .gitignore ]; then
    cat > .gitignore << 'EOF'
# Dependencies
node_modules/
npm-debug.log*

# Environment
.env
.env.local

# Build outputs
dist/
build/
*.log

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Testing
coverage/
playwright-report/
test-results/

# Generated
frontend/
backend/
*.figma
EOF
    log_success "Created .gitignore"
  fi

  # Create initial README
  if [ ! -f README.md ] || [ ! -s README.md ]; then
    cat > README.md << EOF
# $REPO_NAME

$DESCRIPTION

## 🚀 Quick Start

This landing page was generated using the SaaS Validation System.

## 📊 Status

- **Created:** $(date +%Y-%m-%d)
- **Variant:** main
- **URL:** [TBD - Update after deployment]

## 🎯 Next Steps

1. Review generated content
2. Test email capture
3. Deploy to production
4. Monitor conversion rate

---

Generated by [SaaS Validation System](https://github.com/your-org/saas-validation-system)
EOF
    log_success "Created README.md"
  fi
}

setup_main_branch() {
  log_info "Setting up main branch"

  # Initialize git if not already
  if [ ! -d .git ]; then
    git init
    git branch -M main
  fi

  # Add all files
  git add .

  # Initial commit
  if git diff --staged --quiet; then
    log_warn "No changes to commit"
  else
    git commit -m "feat: initialize $REPO_NAME

- Generated landing page structure
- Added documentation
- Configured CI/CD pipeline
- Ready for testing and deployment"
    log_success "Initial commit created"
  fi

  # Push to main
  git push -u origin main
  log_success "Pushed to main branch"
}

# ============================================================================
# BRANCH MANAGEMENT
# ============================================================================

create_feature_branch() {
  local branch_name=$1

  log_info "Creating feature branch: $branch_name"

  # Create and checkout branch
  git checkout -b "$branch_name"

  # Push to remote
  git push -u origin "$branch_name"

  log_success "Feature branch created: $branch_name"
}

list_branches() {
  log_info "Listing all branches"

  echo ""
  echo "Local branches:"
  git branch -v

  echo ""
  echo "Remote branches:"
  git branch -r
}

switch_branch() {
  local branch_name=$1

  log_info "Switching to branch: $branch_name"

  # Check if branch exists locally
  if git show-ref --verify --quiet refs/heads/"$branch_name"; then
    git checkout "$branch_name"
  else
    # Check if branch exists remotely
    if git show-ref --verify --quiet refs/remotes/origin/"$branch_name"; then
      git checkout "$branch_name"
    else
      log_error "Branch '$branch_name' not found"
      log_info "Available branches:"
      git branch -v
      exit 1
    fi
  fi

  log_success "Switched to: $branch_name"
}

delete_branch() {
  local branch_name=$1

  log_warn "Deleting branch: $branch_name"

  # Delete local branch
  git branch -d "$branch_name" 2>/dev/null || true

  # Delete remote branch
  git push origin --delete "$branch_name" 2>/dev/null || true

  log_success "Branch deleted: $branch_name"
}

# ============================================================================
# BRANCHING STRATEGY
# ============================================================================

setup_branching_strategy() {
  log_info "Setting up branching strategy"

  # Main branch (production)
  if ! git show-ref --verify --quiet refs/heads/main; then
    git checkout -b main
  fi

  # Develop branch (staging)
  if ! git show-ref --verify --quiet refs/heads/develop; then
    git checkout -b develop
    git push -u origin develop
    log_success "Created develop branch"
  fi

  # Return to main
  git checkout main

  log_success "Branching strategy configured"
  log_info "Branches: main (production), develop (staging), feature/* (features)"
}

# ============================================================================
# PULL REQUEST MANAGEMENT
# ============================================================================

create_pull_request() {
  local title=$1
  local body=$2
  local from_branch=${3:-$(git branch --show-current)}
  local to_branch=${4:-"main"}

  log_info "Creating pull request: $from_branch → $to_branch"

  gh pr create \
    --title "$title" \
    --body "$body" \
    --base "$to_branch" \
    --head "$from_branch"

  log_success "Pull request created"
}

list_pull_requests() {
  log_info "Listing pull requests"

  gh pr list
}

merge_pull_request() {
  local pr_number=$1

  log_info "Merging PR #$pr_number"

  gh pr merge "$pr_number" --merge --delete-branch

  log_success "PR merged and branch deleted"
}

# ============================================================================
# ISSUE MANAGEMENT
# ============================================================================

create_issue() {
  local title=$1
  local body=${2:-""}

  log_info "Creating issue: $title"

  gh issue create \
    --title "$title" \
    --body "$body"

  log_success "Issue created"
}

list_issues() {
  log_info "Listing issues"

  gh issue list
}

# ============================================================================
# WORKFLOW MANAGEMENT
# ============================================================================

enable_workflow() {
  local workflow_file=$1

  log_info "Enabling workflow: $workflow_file"

  # GitHub Actions workflows are enabled by default when pushed
  log_success "Workflow will be enabled on push"
}

list_workflows() {
  log_info "Listing workflows"

  gh workflow list
}

# ============================================================================
# COLLABORATION
# ============================================================================

add_collaborator() {
  local username=$1
  local permission=${2:-"write"}

  log_info "Adding collaborator: $username"

  gh api \
    --method PUT \
    -H "Accept: application/vnd.github.v3+json" \
    "/repos/:owner/:repo/collaborators/$username" \
    -f permission="$permission"

  log_success "Collaborator added: $username"
}

# ============================================================================
# UTILITIES
# ============================================================================

get_repo_info() {
  log_info "Repository information"

  gh repo view --web
}

open_repo() {
  log_info "Opening repository in browser"

  gh repo view --web
}

clone_repo() {
  local repo_url=$1
  local directory=${2:-""}

  log_info "Cloning repository: $repo_url"

  if [ -n "$directory" ]; then
    git clone "$repo_url" "$directory"
  else
    git clone "$repo_url"
  fi

  log_success "Repository cloned"
}

# ============================================================================
# MAIN MENU
# ============================================================================

show_help() {
  cat << 'EOFHELP'
GitHub Repository Management for SaaS Validation System

Usage: ./github-setup.sh <command> [options]

Commands:
  create <repo-name> [description] [visibility]  Create new repository
  init                                          Initialize repository structure
  branch <branch-name>                          Create feature branch
  switch <branch-name>                          Switch to branch
  delete <branch-name>                          Delete branch
  pr-create "title" "body" [from] [to]          Create pull request
  pr-list                                       List pull requests
  pr-merge <pr-number>                          Merge pull request
  issue-create "title" "body"                   Create issue
  issue-list                                    List issues
  setup-strategy                                Setup branching strategy
  clone <repo-url> [directory]                  Clone repository
  info                                          Show repository info
  open                                          Open repository in browser
  help                                          Show this help

Examples:
  # Create new repository
  ./github-setup.sh create "my-saas-idea" "AI Invoice Validator" private

  # Initialize existing project
  ./github-setup.sh init

  # Create feature branch
  ./github-setup.sh branch "feature/new-cta"

  # Switch branches
  ./github-setup.sh switch "develop"

  # Create pull request
  ./github-setup.sh pr-create "Add new CTA" "Implements new call-to-action" feature/new-cta main

  # Setup branching strategy
  ./github-setup.sh setup-strategy

For more information, see: https://docs.github.com
EOFHELP
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

main() {
  if [ -z "${1:-}" ]; then
    show_help
    exit 0
  fi

  local command=$1
  shift

  case $command in
    create)
      check_gh_cli
      if [ -z "${1:-}" ]; then
        log_error "Repository name required"
        echo "Usage: $0 create <repo-name> [description] [visibility]"
        exit 1
      fi
      REPO_NAME=$1
      DESCRIPTION=${2:-"AI-generated landing page for SaaS validation"}
      VISIBILITY=${3:-"private"}
      create_repository
      initialize_repository
      setup_main_branch
      ;;
    init)
      check_gh_cli
      initialize_repository
      setup_main_branch
      ;;
    branch)
      if [ -z "${1:-}" ]; then
        log_error "Branch name required"
        echo "Usage: $0 branch <branch-name>"
        exit 1
      fi
      create_feature_branch "$1"
      ;;
    switch)
      if [ -z "${1:-}" ]; then
        log_error "Branch name required"
        echo "Usage: $0 switch <branch-name>"
        exit 1
      fi
      switch_branch "$1"
      ;;
    delete)
      if [ -z "${1:-}" ]; then
        log_error "Branch name required"
        echo "Usage: $0 delete <branch-name>"
        exit 1
      fi
      delete_branch "$1"
      ;;
    pr-create)
      check_gh_cli
      if [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
        log_error "Title and body required"
        echo "Usage: $0 pr-create \"title\" \"body\" [from-branch] [to-branch]"
        exit 1
      fi
      create_pull_request "$1" "$2" "${3:-}" "${4:-main}"
      ;;
    pr-list)
      check_gh_cli
      list_pull_requests
      ;;
    pr-merge)
      check_gh_cli
      if [ -z "${1:-}" ]; then
        log_error "PR number required"
        echo "Usage: $0 pr-merge <pr-number>"
        exit 1
      fi
      merge_pull_request "$1"
      ;;
    issue-create)
      check_gh_cli
      if [ -z "${1:-}" ]; then
        log_error "Title required"
        echo "Usage: $0 issue-create \"title\" [\"body\"]"
        exit 1
      fi
      create_issue "$1" "${2:-}"
      ;;
    issue-list)
      check_gh_cli
      list_issues
      ;;
    setup-strategy)
      setup_branching_strategy
      ;;
    clone)
      if [ -z "${1:-}" ]; then
        log_error "Repository URL required"
        echo "Usage: $0 clone <repo-url> [directory]"
        exit 1
      fi
      clone_repo "$1" "${2:-}"
      ;;
    info)
      check_gh_cli
      get_repo_info
      ;;
    open)
      check_gh_cli
      open_repo
      ;;
    help|--help|-h)
      show_help
      ;;
    *)
      log_error "Unknown command: $command"
      show_help
      exit 1
      ;;
  esac
}

main "$@"
